FROM node:22-alpine as build
WORKDIR /app/frontend

COPY package*.json ./
RUN npm ci --omit=optional
RUN npm install @rollup/rollup-linux-x64-musl --save-optional

COPY . .

# Изменим владельца файлов на пользователя node
RUN chown -R node:node /app/frontend

USER node
RUN npm run build