# Stage 1: Build
FROM node:22-alpine AS builder

WORKDIR /app

# Копируем package файлы
COPY package*.json ./

# Устанавливаем ВСЕ зависимости для сборки
RUN npm ci

# Копируем исходный код
COPY . .

# Копируем папку public с картинками
COPY ./public ./public

# Собираем проект
RUN npm run build

# Stage 2: Production
FROM node:22-alpine

WORKDIR /app

# Копируем package файлы для production зависимостей
COPY package*.json ./

# Устанавливаем ТОЛЬКО production зависимости
RUN npm ci --only=production

# Копируем собранные файлы из builder stage
COPY --from=builder /app/dist ./dist

# Копируем package.json если нужны другие файлы
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000
CMD ["node", "dist/src/main.js"]